import { WorkEntry } from './types';

export const INITIAL_WORK_ENTRIES: WorkEntry[] = [
  {
    id: '1',
    date: '2023-10-01',
    customerName: 'Acme Corporation Ltd.',
    areaOfWork: 'GST Filing',
    subParticular: 'GSTR-3B Monthly',
    assignedTo: 'John Doe',
    assignedToInitials: 'JD',
    assignedDate: '2023-10-01',
    status: 'Completed',
    billed: 'Yes',
    invoiceNo: 'INV-2023-001',
    amount: 5000,
    paymentStatus: 'Received',
  },
  {
    id: '2',
    date: '2023-10-02',
    customerName: 'Global Logistics Svc',
    areaOfWork: 'Audit',
    subParticular: 'Statutory Audit',
    assignedTo: 'Jane Smith',
    assignedToInitials: 'JS',
    assignedDate: '2023-10-02',
    status: 'Pending Approval',
    billed: 'No',
    invoiceNo: '—',
    amount: 15000,
    paymentStatus: 'Not Received',
  },
  {
    id: '3',
    date: '2023-10-03',
    customerName: 'Local Retail Shop',
    areaOfWork: 'IT Return',
    subParticular: 'Individual ITR-3',
    assignedTo: 'John Doe',
    assignedToInitials: 'JD',
    assignedDate: '2023-10-03',
    status: 'Assigned',
    billed: 'No',
    invoiceNo: '—',
    amount: 2000,
    paymentStatus: 'Not Received',
  },
  {
    id: '4',
    date: '2023-10-04',
    customerName: 'Tech Inovate Inc.',
    areaOfWork: 'TDS Filing',
    subParticular: 'Salary TDS Quarterly',
    assignedTo: 'Jane Smith',
    assignedToInitials: 'JS',
    assignedDate: '2023-10-04',
    status: 'Initiated',
    billed: 'Yes',
    invoiceNo: 'INV-2023-014',
    amount: 8000,
    paymentStatus: 'Received',
  },
  {
    id: '5',
    date: '2023-10-05',
    customerName: 'Blue Horizon Realty',
    areaOfWork: 'Consulting',
    subParticular: 'Financial Advisory',
    assignedTo: 'John Doe',
    assignedToInitials: 'JD',
    assignedDate: '2023-10-05',
    status: 'Document Requested',
    billed: 'No',
    invoiceNo: '—',
    amount: 10000,
    paymentStatus: 'Not Received',
  },
  {
    id: '6',
    date: '2023-10-06',
    customerName: 'Sky High Builders',
    areaOfWork: 'RERA Compliance',
    subParticular: 'Quarterly Update',
    assignedTo: 'Unassigned',
    assignedToInitials: '',
    assignedDate: '—',
    status: 'Not Assigned',
    billed: 'No',
    invoiceNo: '—',
    amount: 12500,
    paymentStatus: 'Not Received',
  }
];
